.TH "memsim_entry_t" 3 "Sat Jan 25 2014" "Version 1.0" "MEM_SIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memsim_entry_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBbuf\fP [4]"
.br
.ti -1c
.RI "uint64_t \fBgconst\fP"
.br
.ti -1c
.RI "uint32_t \fBvalid\fP"
.br
.ti -1c
.RI "memsim_rqst_t \fBrqst\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint64_t memsim_entry_t::gconst"
MEM-SIM: MEMSIM_ENTRY_T: BUFFER 
.SS "memsim_rqst_t memsim_entry_t::rqst"
MEM-SIM: MEMSIM_ENTRY_T: VALID BIT 
.SS "uint32_t memsim_entry_t::valid"
MEM-SIM: MEMSIM_ENTRY_T: GCONST 

.SH "Author"
.PP 
Generated automatically by Doxygen for MEM_SIM from the source code\&.
