.TH "memsim_slot_t" 3 "Sat Feb 8 2014" "Version 1.0" "MEM_SIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memsim_slot_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBmemsim_entry_t\fP * \fBentry\fP"
.br
.ti -1c
.RI "uint32_t \fBnum_slots\fP"
.br
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t memsim_slot_t::id"
MEM-SIM: MEMSIM_SLOT_T: NUMBER OF SLOTS 
.SS "uint32_t memsim_slot_t::num_slots"
MEM-SIM: MEMSIM_SLOT_T: ENTRIES 

.SH "Author"
.PP 
Generated automatically by Doxygen for MEM_SIM from the source code\&.
