.TH "hmc_dram_t" 3 "Sat Aug 31 2013" "Version 1.0" "HMC_SIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmc_dram_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBelems\fP [8]"
.br
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t hmc_dram_t::id"
HMC-SIM: HMC_DRAM_T: DRAM ELEMENTS 

.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_SIM from the source code\&.
