.TH "hmc_vault_t" 3 "Sat Jan 25 2014" "Version 1.0" "HMC_SIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmc_vault_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBhmc_bank_t\fP * \fBbanks\fP"
.br
.ti -1c
.RI "struct \fBhmc_queue_t\fP * \fBrqst_queue\fP"
.br
.ti -1c
.RI "struct \fBhmc_queue_t\fP * \fBrsp_queue\fP"
.br
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t hmc_vault_t::id"
HMC-SIM: HMC_VAULT_T: REQUEST PACKET QUEUE 
.SS "struct \fBhmc_queue_t\fP* hmc_vault_t::rqst_queue"
HMC-SIM: HMC_VAULT_T: BANK STRUCTURE 
.SS "struct \fBhmc_queue_t\fP* hmc_vault_t::rsp_queue"
HMC-SIM: HMC_VAULT_T: REQUEST PACKET QUEUE 

.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_SIM from the source code\&.
