.TH "hmc_reg_t" 3 "Sat Jan 25 2014" "Version 1.0" "HMC_SIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmc_reg_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "hmc_reg_def_t \fBtype\fP"
.br
.ti -1c
.RI "uint64_t \fBphy_idx\fP"
.br
.ti -1c
.RI "uint64_t \fBreg\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint64_t hmc_reg_t::phy_idx"
HMC-SIM: HMC_REG_T: REGISTER TYPE 
.SS "uint64_t hmc_reg_t::reg"
HMC-SIM: HMC_REG_T: REGISTER PHYSICAL DEVICE INDEX 

.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_SIM from the source code\&.
