.TH "hmc_dev_t" 3 "Wed Sep 11 2013" "Version 1.0" "HMC_SIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmc_dev_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBhmc_link_t\fP * \fBlinks\fP"
.br
.ti -1c
.RI "struct \fBhmc_quad_t\fP * \fBquads\fP"
.br
.ti -1c
.RI "struct \fBhmc_xbar_t\fP * \fBxbar\fP"
.br
.ti -1c
.RI "struct \fBhmc_reg_t\fP \fBregs\fP [HMC_NUM_REGS]"
.br
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.ti -1c
.RI "uint8_t \fBseq\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t hmc_dev_t::id"
HMC-SIM: HMC_DEV_T: DEVICE CONFIGURATION REGISTERS 
.SS "struct \fBhmc_reg_t\fP hmc_dev_t::regs[HMC_NUM_REGS]"
HMC-SIM: HMC_DEV_T: CROSSBAR STRUCTURE 
.SS "uint8_t hmc_dev_t::seq"
HMC-SIM: HMC_DEV_T: CUBE ID 
.SS "struct \fBhmc_xbar_t\fP* hmc_dev_t::xbar"
HMC-SIM: HMC_DEV_T: QUADRANT STRUCTURE 

.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_SIM from the source code\&.
