/*
 * _GOBLIN_SIM_MACROS_H_
 * 
 * GOBLIN-SIM MACROS HEADER FILE 
 * 
 * WARNING: DO NOT INCLUDE THIS FILE DIRECTLY
 *          ALWAYS USE THE TOP-LEVEL HEADER: 
 *          GOBLIN_SIM.H
 * 
 */


#ifndef	_GOBLIN_SIM_MACROS_H_
#define _GOBLIN_SIM_MACROS_H_

#ifdef __cplusplus
extern "C" {
#endif


/* --------------------------------------------- VERSION MACROS */
#ifndef GSIM_MAJOR_VERSION
#define GSIM_MAJOR_VERSION	0
#endif

#ifndef GSIM_MINOR_VERSION
#define GSIM_MINOR_VERSION	1
#endif

#ifndef GSIM_SVN_VERSION
#define GSIM_SVN_VERSION	0000
#endif


/* --------------------------------------------- SIMULATION OPTION MACROS */
#define	GSIM_OPT_TRACING	0x0000000000000001	/*! RUNTIME OPTIONS: ENABLE TRACING */
#define GSIM_OPT_EXCEPTIONS	0x0000000000000002	/*! RUNTIME OPTIONS: ENABLE EXCEPTIONS */
#define GSIM_OPT_TASKING	0x0000000000000004	/*! RUNTIME OPTIONS: ENABLE TASKING */

#define	GSIM_OPT_CYCLE_FUNC	0x0000000000000008	/*! RUNTIME OPTIONS: ENABLE FUNCTIONAL SIM */
#define	GSIM_OPT_CYCLE_ACCUR	0x000000000000000F	/*! RUNTIME OPTIONS: ENABLE CYCLE ACCURATE CXX SIM */
#define	GSIM_OPT_CYCLE_HDL	0x0000000000000010	/*! RUNTIME OPTIONS: ENABLE VERILOG SIM */

#define GSIM_OPT_GLOBAL_ADDR	0x0000000000000020	/*! RUNTIME OPTIONS: ENABLE GLOBAL ADDRESSING */
#define GSIM_OPT_VECTOR		0x0000000000000040	/*! RUNTIME OPTIONS: ENABLE VECTOR ALU */

#define GSIM_OPT_DUMPINST	0x8000000000000000	/*! RUNTIME OPTIONS: DUMP ALL VALID INSTRUCTIONS */
#define GSIM_OPT_VALIDATE	0xF000000000000000	/*! RUNTIME OPTIONS: VALIDATE THE OBJECT */


/* --------------------------------------------- SIMULATION DEFAULTS */
#define GSIM_OPT_DEFAULT	(GSIM_OPT_EXCEPTIONS|GSIM_OPT_TASKING|GSIM_OPT_CYCLE_FUNC)
#define	GSIM_DEFAULT_STACK_SIZE	4194304			/* DEFAULT OPTIONS: 4MB STACKS */

/* --------------------------------------------- SIMULATION PROC STATES */
#define GSIM_PROC_STATE_DISABLED	0xFFFFFFFFFFFFFFFF	/*! PROC STATES: PROC DISABLED : NO CONTEXT */
#define GSIM_PROC_STATE_ENABLED 	0x0000000000000001	/*! PROC STATES: PROC ENABLED : CONTEXT */

/* --------------------------------------------- PRINT MACROS */
#define	GSIM_PRINT_ERROR( s )		( fprintf( stderr, "GSIM_ERROR: %s:%d : %s\n", __FUNCTION__, __LINE__, s ) )
#define	GSIM_PRINT_MSG( s )		( fprintf( stdout, "GSIM_MSG: %s:%d : %s\n", __FUNCTION__, __LINE__, s ) )
#define	GSIM_PRINT_U8_MSG( s, d )	( fprintf( stdout, "GSIM_MSG: %s:%d : %s:0x%016llx\n", __FUNCTION__, __LINE__, s, d ) )
#define	GSIM_PRINT_FUNC_ENTRY( )	( fprintf( stdout, "GSIM_FUNC_ENTRY: %s:%s:%d\n", __FILE__, __FUNCTION__ , __LINE__ ) )
#define	GSIM_PRINT_FUNC_EXIT( )		( fprintf( stdout, "GSIM_FUNC_EXIT : %s:%s:%d\n", __FILE__, __FUNCTION__, __LINE__ ) )

#ifdef __cplusplus
} /* extern C */
#endif

#endif	/* _GOBLIN_SIM_MACROS_H_ */

/* EOF */
